In [1]:
import networkx as nx 
import numpy as np
from numpy.linalg import norm
from  math  import *
import pandas as pd
from sklearn.metrics import pairwise_distances_argmin
from sklearn.metrics import pairwise_distances
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
top10= pd.read_csv("top10_result_Email.csv")

In [3]:
G1=nx.read_edgelist('Email.txt',create_using=nx.Graph(),nodetype=int)

In [4]:
G1 = nx.read_edgelist("Email.txt", nodetype = int)
data = pd.read_csv("TOPSIS_result_Email.csv")
x=data[["DC","BC","CC","EC"]]

In [5]:
x

DC        BC        CC        EC
0     0.062721  0.036931  0.378216  0.229103
1     0.045936  0.039490  0.382820  0.123657
2     0.045053  0.033463  0.381659  0.116593
3     0.045053  0.026024  0.377585  0.131570
4     0.037986  0.030118  0.374339  0.082444
...        ...       ...       ...       ...
1128  0.000883  0.000000  0.189965  0.000040
1129  0.000883  0.000000  0.186154  0.000025
1130  0.000883  0.000000  0.185513  0.000022
1131  0.000883  0.000000  0.184545  0.000030
1132  0.000883  0.000000  0.182169  0.000014

[1133 rows x 4 columns]

In [6]:
def Sn(data ):
  DC=[]
  BC=[]
  EC=[]
  CC=[]
  A=[]
  DCEb=[]

  DC=data['DC']
  BC=data['BC']
  EC=data['EC']
  CC=data['CC']
  for i in range(len(BC)):
    DCEB=(DC[i]+EC[i]+BC[i]+CC[i])/4
    A.append(DCEB)
  return A



data=pd.read_csv('TOPSIS_result_Email.csv')
SN=Sn(data)
data['SN']=SN

data.to_csv('moyen_Email.csv')

In [ ]:
SN

[0.1767426828573316,
 0.14797584685431298,
 0.14419189523250672,
 0.14505814606340373,
 0.13122146188060296,
 0.13723107382400684,
 0.11928610069989203,
 0.13022014938087634,
 0.1433891680481333,
 0.12500699869062604,
 0.14369823061337567,
 0.12028025684778502,
 0.12604187529806762,
 0.12760278049403323,
 0.1314208563160673,
 0.11158280868364823,
 0.12019546021568167,
 0.13197374902318,
 0.11365152263169635,
 0.11671685451599981,
 0.1118420706766628,
 0.11326583414436273,
 0.12180195876146722,
 0.12915199233609437,
 0.10509656229542075,
 0.10906097704858006,
 0.13077656568818014,
 0.12444249675927607,
 0.11798932843487078,
 0.1123151257696396,
 0.1208177879913406,
 0.13277753873836806,
 0.12892405768818463,
 0.12359831873344992,
 0.09813544997289204,
 0.1036777153974938,
 0.11089214574339992,
 0.0952664645829632,
 0.10199362424260783,
 0.12775025457498357,
 0.1042757898226653,
 0.10970837629448467,
 0.11046785274428036,
 0.11377263856806555,
 0.11617819331366591,
 0.10409589009697372,


In [7]:
data.drop(columns=['TOPSIS'], inplace=True)
data
AA=pd.read_csv('TOPSIS_result_Email.csv')
inf10=AA.head(10)
inf10

node        DC        CC        BC        EC    TOPSIS
0   104  0.062721  0.378216  0.036931  0.229103  0.949770
1   332  0.045936  0.382820  0.039490  0.123657  0.774723
2    22  0.045053  0.381659  0.033463  0.116593  0.719794
3    41  0.045053  0.377585  0.026024  0.131570  0.643457
4    75  0.037986  0.374339  0.030118  0.082444  0.622879
5    40  0.043286  0.374959  0.026499  0.104180  0.613028
6   577  0.032686  0.359822  0.031557  0.053080  0.593461
7   232  0.039753  0.373351  0.027717  0.080060  0.593178
8   195  0.041519  0.358001  0.019789  0.154247  0.564735
9   134  0.035336  0.369935  0.027264  0.067493  0.564543

In [8]:
Y=inf10[["DC","BC","CC","EC"]]
Yrr=Y.to_numpy()
Yrr


array([[0.06272085, 0.03693125, 0.37821584, 0.2291028 ],
       [0.0459364 , 0.03948986, 0.38282043, 0.12365671],
       [0.045053  , 0.03346298, 0.3816588 , 0.1165928 ],
       [0.045053  , 0.02602442, 0.37758506, 0.13157011],
       [0.03798587, 0.0301175 , 0.37433862, 0.08244386],
       [0.04328622, 0.02649936, 0.3749586 , 0.10418012],
       [0.03268551, 0.03155663, 0.359822  , 0.05308027],
       [0.03975265, 0.02771703, 0.37335092, 0.08005999],
       [0.04151943, 0.01978877, 0.35800127, 0.15424721],
       [0.03533569, 0.02726447, 0.36993464, 0.0674932 ]])

In [9]:
def kmeans(X, k, maxiter,yrr, seed = None):
  
    n_row, n_col = X.shape

   
    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr

    for itr in range(maxiter):
        
        distances_to_centroids = pairwise_distances(X, centroids, metric = 'euclidean')
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

       
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
     
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [10]:
centers, label = kmeans(x.values,10,20000,Yrr)

In [11]:
centers

array([[6.27208481e-02, 3.69312485e-02, 3.78215837e-01, 2.29102798e-01],
       [3.59430212e-02, 2.19259013e-02, 3.67869611e-01, 9.32170489e-02],
       [2.37846665e-02, 1.05586202e-02, 3.42329471e-01, 5.25199230e-02],
       [1.82914155e-02, 3.77762374e-03, 3.16818085e-01, 5.91094068e-02],
       [1.44375297e-02, 4.23508511e-03, 3.20020054e-01, 2.85573526e-02],
       [8.74677146e-03, 1.82295129e-03, 2.95809852e-01, 1.55796654e-02],
       [1.34612149e-03, 8.27090855e-05, 2.22301144e-01, 6.18437034e-04],
       [5.08846961e-03, 6.29413754e-04, 2.74658031e-01, 7.25981144e-03],
       [2.99764429e-02, 9.01461370e-03, 3.42704596e-01, 1.20249453e-01],
       [2.63865417e-03, 1.87546748e-04, 2.52301034e-01, 2.78881159e-03]])

In [12]:
def distance_euclidean(data,center,j):
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [13]:
Res1= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centers,i)
  Res1=Res1.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_ after _KMeans':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [15]:
Res1

cluster Node_before_KMeans  Node_ after _KMeans  distance from center
0       0                104                104.0              0.000000
1       1                332                 53.0              0.013519
2       2                 22                181.0              0.002979
3       3                 41                321.0              0.004551
4       4                 75                239.0              0.001688
5       5                 40                742.0              0.001441
6       6                577                501.0              0.000566
7       7                232                718.0              0.001191
8       8                195                 55.0              0.007047
9       9                134               1010.0              0.000847

In [ ]:
#ref f2 k means

In [16]:
def dis(SN):
 dist0=[]
 ce=[]
 min = 13000
 for i in range(0,10):
         for j in range(len(SN)):
           dist=sqrt(pow(SN[i],2)+pow(SN[j],2))
           dist0.append(dist)
           A=dist0
 n=10 
 B=[A[i:i+n] for i in range(0,len(A),n)]
 return B
dst=dis(SN)


In [17]:
dst1= np.asarray(dst)
dst1

array([[0.2499519 , 0.23050993, 0.22809927, ..., 0.2195342 , 0.22759268,
        0.21648262],
       [0.22778753, 0.21378802, 0.21708185, ..., 0.22057889, 0.21013007,
        0.21180368],
       [0.20915694, 0.20992171, 0.21464784, ..., 0.21615714, 0.21250755,
        0.20941028],
       ...,
       [0.13608433, 0.13602706, 0.13603267, ..., 0.13584909, 0.13580269,
        0.13580352],
       [0.13579728, 0.13569499, 0.13564041, ..., 0.13480736, 0.13476377,
        0.13475312],
       [0.1347364 , 0.13470698, 0.13466632, ..., 0.1334119 , 0.13332829,
        0.13312156]])

In [18]:
def kmeans(X, k, maxiter,yrr,distance,seed = None):
  
    n_row, n_col = X.shape

   
    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr

    for itr in range(maxiter):
       
        distances_to_centroids = distance
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

       
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
        
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [19]:
centroids, cluster_assignment=kmeans(x.values,10,20000,Yrr,dst1)

In [20]:
centroids

array([[0.00841186, 0.00219588, 0.28346295, 0.01669427],
       [0.00811201, 0.00221608, 0.27851396, 0.01703836],
       [0.00916638, 0.0023946 , 0.28564223, 0.02036594],
       [0.00805446, 0.00192511, 0.28128819, 0.01763394],
       [0.01046736, 0.00308591, 0.28840844, 0.02290351],
       [0.00967122, 0.00315795, 0.28575633, 0.01985224],
       [0.00801678, 0.00212568, 0.27921096, 0.01718707],
       [0.00834154, 0.00209355, 0.28180071, 0.0169203 ],
       [0.00773852, 0.00190633, 0.28086513, 0.01555864],
       [0.00764372, 0.00208861, 0.27772428, 0.01455593]])

In [21]:
def distance_euclidean(data,center,j):
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [22]:
Res= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centroids,i)
  Res=Res.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_ after _KMeans  with score':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [23]:
Res

cluster Node_before_KMeans  Node_ after _KMeans  with score  \
0       0                104                            140.0   
1       1                332                            592.0   
2       2                 22                            642.0   
3       3                 41                            592.0   
4       4                 75                            440.0   
5       5                 40                            889.0   
6       6                577                            592.0   
7       7                232                            592.0   
8       8                195                            165.0   
9       9                134                            322.0   

   distance from center  
0              0.003351  
1              0.001702  
2              0.003759  
3              0.003055  
4              0.002391  
5              0.004371  
6              0.001691  
7              0.003690  
8              0.002607  
9              0.002650

In [24]:
top10=pd.read_csv("top10_result_Email.csv")

In [25]:
top10

Unnamed: 0   DC   BC   CC   EC  TOPSIS
0           0  104  104  104  104     104
1           1  332  332  332  332     332
2           2   22   22   22   41      22
3           3   41   41   41  195      41
4           4   40   75   75   15      75
5           5  577   40   40   48      40
6           6  232  577  232  115     577
7           7  195  232  134  203     232
8           8   15  134  377    2     195
9           9  377  354   51   55     134

In [26]:
top10["k_means"]=Res1["Node_ after _KMeans"]
top10["k_means with score"]=Res["Node_ after _KMeans  with score"]
top10

Unnamed: 0   DC   BC   CC   EC  TOPSIS  k_means  k_means with score
0           0  104  104  104  104     104    104.0               140.0
1           1  332  332  332  332     332     53.0               592.0
2           2   22   22   22   41      22    181.0               642.0
3           3   41   41   41  195      41    321.0               592.0
4           4   40   75   75   15      75    239.0               440.0
5           5  577   40   40   48      40    742.0               889.0
6           6  232  577  232  115     577    501.0               592.0
7           7  195  232  134  203     232    718.0               592.0
8           8   15  134  377    2     195     55.0               165.0
9           9  377  354   51   55     134   1010.0               322.0

In [28]:
top10.to_csv("score_Email.csv")