In [2]:
import networkx as nx 
import numpy as np
from numpy.linalg import norm
from  math  import *
import pandas as pd
from sklearn.metrics import pairwise_distances_argmin
from sklearn.metrics import pairwise_distances
import matplotlib.pyplot as plt
%matplotlib inline


In [3]:
top10= pd.read_csv("top10_result_dolphine1.csv")
top10

Unnamed: 0  DC  BC  CC  EC  TOPSIS
0           0  36  36  36  37      36
1           1  14   1   1  40       1
2           2  54  37  37  14      37
3           3  43  40  40  51      40
4           4  50  20  20  33      20
5           5  15  51  14  45      14
6           6  18  17   7  29      51
7           7  52   7  33  50      17
8           8   9  54  28  21       7
9           9  44  57   8  16      33

In [4]:
G1=nx.read_edgelist('dolphins.txt',create_using=nx.Graph(),nodetype=int)

In [5]:
G1 = nx.read_edgelist("dolphins.txt", nodetype = int)
data = pd.read_csv("TOPSIS_result_dolphins.csv")
x=data[["DC","BC","CC","EC"]]

In [6]:
x

DC        BC        CC        EC
0   0.114754  0.248237  0.417808  0.132766
1   0.131148  0.213324  0.371951  0.042091
2   0.180328  0.138570  0.398693  0.300561
3   0.131148  0.143150  0.403974  0.207873
4   0.147541  0.102646  0.391026  0.184478
..       ...       ...       ...       ...
57  0.016393  0.000000  0.237354  0.002438
58  0.016393  0.000000  0.237354  0.002438
59  0.016393  0.000000  0.232824  0.002420
60  0.032787  0.000137  0.213287  0.002612
61  0.016393  0.000000  0.178363  0.000537

[62 rows x 4 columns]

In [7]:
def Sn(data ):
  DC=[]
  BC=[]
  CC=[]
  A=[]
  DCEb=[]

  DC=data['DC']
  BC=data['BC']
  CC=data['CC']
  for i in range(len(BC)):
    DCB=(DC[i]+BC[i]+CC[i])/3
    A.append(DCB)
  return A



data=pd.read_csv('TOPSIS_result_dolphins.csv')
SN=Sn(data)
data['SN']=SN



In [ ]:
SN

[0.2602665045225587,
 0.23880773200953753,
 0.23919682265618988,
 0.22609018975333292,
 0.2137374547843693,
 0.21174550873360234,
 0.1927804702364878,
 0.19049527219092943,
 0.18849176448732727,
 0.19545677580820406,
 0.18919640617994607,
 0.17860719628479185,
 0.179447943410186,
 0.17790862168710508,
 0.17153375912508537,
 0.16874316984972718,
 0.1662466153105874,
 0.17133120961885165,
 0.16231173607725927,
 0.15554185755441532,
 0.14615616631689024,
 0.1481315476670668,
 0.15170166017780304,
 0.14379836510984048,
 0.13952140401593952,
 0.16127387714378405,
 0.1435747163278379,
 0.1546780536807859,
 0.14156548228031393,
 0.15241611247075723,
 0.14250158153178963,
 0.1483322056728739,
 0.15348367358203424,
 0.14592299887928298,
 0.14242208325790504,
 0.13175901737817144,
 0.12923819814157614,
 0.13695991561565332,
 0.1342599297982321,
 0.1296120220456676,
 0.1198783108209337,
 0.13165011360815312,
 0.0994264232841142,
 0.12178516950055655,
 0.11901799677755957,
 0.1015918219606744,
 0.

In [8]:
data.drop(columns=['TOPSIS'], inplace=True)
data
AA=pd.read_csv('TOPSIS_result_dolphins.csv')
inf10=AA.head(10)
inf10

node        DC        CC        BC        EC    TOPSIS
0    36  0.114754  0.417808  0.248237  0.132766  0.785091
1     1  0.131148  0.371951  0.213324  0.042091  0.684360
2    37  0.180328  0.398693  0.138570  0.300561  0.634847
3    40  0.131148  0.403974  0.143150  0.207873  0.601404
4    20  0.147541  0.391026  0.102646  0.184478  0.476616
5    14  0.196721  0.376543  0.061972  0.315781  0.448741
6    51  0.163934  0.329730  0.084677  0.210680  0.438142
7    17  0.147541  0.309645  0.114300  0.017535  0.435038
8     7  0.081967  0.365269  0.118239  0.042908  0.434302
9    33  0.163934  0.365269  0.057166  0.281097  0.410053

In [9]:
Y=inf10[["DC","BC","CC","EC"]]
Yrr=Y.to_numpy()
Yrr


array([[0.1147541 , 0.2482372 , 0.41780822, 0.13276551],
       [0.13114754, 0.21332444, 0.37195122, 0.04209144],
       [0.18032787, 0.13856979, 0.39869281, 0.30056093],
       [0.13114754, 0.14314952, 0.40397351, 0.20787263],
       [0.14754098, 0.10264574, 0.39102564, 0.18447787],
       [0.19672131, 0.061972  , 0.37654321, 0.31578108],
       [0.16393443, 0.08467725, 0.32972973, 0.21068021],
       [0.14754098, 0.11430016, 0.30964467, 0.01753497],
       [0.08196721, 0.11823862, 0.36526946, 0.04290802],
       [0.16393443, 0.05716644, 0.36526946, 0.28109702]])

In [10]:
def kmeans(X, k, maxiter,yrr, seed = None):
   
    n_row, n_col = X.shape

    # randomly choose k data points as initial centroids
    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr

    for itr in range(maxiter):
        # compute distances between each data point and the set of centroids
        # and assign each data point to the closest centroid
        distances_to_centroids = pairwise_distances(X, centroids, metric = 'euclidean')
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

        # select all data points that belong to cluster i and compute
        # the mean of these data points (each feature individually)
        # this will be our new cluster centroids
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
        # if the updated centroid is still the same,
        # then the algorithm converged
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [11]:
centers, label = kmeans(x.values,10,20000,Yrr)

In [12]:
centers

array([[0.1147541 , 0.2482372 , 0.41780822, 0.13276551],
       [0.12459016, 0.12583791, 0.33466273, 0.02859176],
       [0.18032787, 0.13856979, 0.39869281, 0.30056093],
       [0.13934426, 0.12289763, 0.39749958, 0.19617525],
       [0.0852459 , 0.02274204, 0.34222832, 0.13036305],
       [0.19672131, 0.061972  , 0.37654321, 0.31578108],
       [0.11967213, 0.03633359, 0.33215911, 0.20023088],
       [0.0291439 , 0.00273991, 0.24338171, 0.01828588],
       [0.07810993, 0.02867964, 0.30953279, 0.04673003],
       [0.17213115, 0.04891844, 0.35593019, 0.28305006]])

In [13]:
def distance_euclidean(data,center,j):
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [14]:
Res1= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centers,i)
  Res1=Res1.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_ after _KMeans':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [ ]:
Res1

cluster Node_before_KMeans  Node_ after _KMeans  distance from center
0       0                 36                 36.0              0.000000
1       1                  1                 54.0              0.030748
2       2                 37                 37.0              0.000000
3       3                 40                 40.0              0.025614
4       4                 20                  0.0              0.014418
5       5                 14                 14.0              0.000000
6       6                 51                 38.0              0.015231
7       7                 17                 49.0              0.007472
8       8                  7                 30.0              0.015635
9       9                 33                 45.0              0.015042

In [15]:
def dist(SN):
 dist0=[]
 ce=[]
 min = 13000
 for i in range(0,10):
         for j in range(len(SN)):
           dist=sqrt(pow(SN[i],2)+pow(SN[j],2))
           dist0.append(dist)
           A=dist0
 n=10 
 B=[A[i:i+n] for i in range(0,len(A),n)]
 return B
dst=dist(SN)


In [ ]:
dst

[[0.36807242052724093,
  0.3532248380903163,
  0.3534880101859295,
  0.34475415483948724,
  0.3367823524980063,
  0.33552170398536535,
  0.32388726909372717,
  0.32253232722238456,
  0.3213530747572475,
  0.32548733398663854],
 [0.32176689308845646,
  0.31565675019093953,
  0.31613322788112036,
  0.3152620038111103,
  0.3117089730758065,
  0.31018206064717047,
  0.30883100634265576,
  0.3115975557764373,
  0.3067307500802698,
  0.3032027750992215],
 [0.29849669734997325,
  0.29946887783312565,
  0.3012508042762586,
  0.29734932854246376,
  0.29530471644552186,
  0.30618281601908914,
  0.29724123627957505,
  0.3027605550048869,
  0.296275951014673,
  0.30161121450816375],
 [0.2967243739827457,
  0.2995681835845903,
  0.30215209983157076,
  0.2983825983168494,
  0.2966862032112594,
  0.2917174866833532,
  0.2905876205815938,
  0.29410316533801184,
  0.292855565297669,
  0.2907540707112416],
 [0.2865474878299781,
  0.2916683146819871,
  0.2786113189076547,
  0.2873504496023459,
  0.286188

In [16]:
dst1= np.asarray(dst)
dst1

array([[0.36807242, 0.35322484, 0.35348801, 0.34475415, 0.33678235,
        0.3355217 , 0.32388727, 0.32253233, 0.32135307, 0.32548733],
       [0.32176689, 0.31565675, 0.31613323, 0.315262  , 0.31170897,
        0.31018206, 0.30883101, 0.31159756, 0.30673075, 0.30320278],
       [0.2984967 , 0.29946888, 0.3012508 , 0.29734933, 0.29530472,
        0.30618282, 0.29724124, 0.30276056, 0.29627595, 0.30161121],
       [0.29672437, 0.29956818, 0.3021521 , 0.2983826 , 0.2966862 ,
        0.29171749, 0.29058762, 0.29410317, 0.29285557, 0.29075407],
       [0.28654749, 0.29166831, 0.27861132, 0.28735045, 0.28618864,
        0.2793914 , 0.28266329, 0.27981281, 0.27707579, 0.27954671],
       [0.27805317, 0.27788268, 0.27657203, 0.274888  , 0.274888  ,
        0.274888  , 0.27446188, 0.27366559, 0.27366559, 0.2732027 ],
       [0.27289952, 0.26824073, 0.35322484, 0.33772513, 0.33800037,
        0.32885545, 0.32048843, 0.31916343, 0.3069095 , 0.30547927],
       [0.30423392, 0.30859761, 0.3046709

In [17]:
def kmeans(X, k, maxiter,yrr,distance,seed = None):
    """
    specify the number of clusters k and
    the maximum iteration to run the algorithm
    """
    n_row, n_col = X.shape

    # randomly choose k data points as initial centroids
    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr

    for itr in range(maxiter):
        # compute distances between each data point and the set of centroids
        # and assign each data point to the closest centroid
        distances_to_centroids = distance
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

        # select all data points that belong to cluster i and compute
        # the mean of these data points (each feature individually)
        # this will be our new cluster centroids
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
        # if the updated centroid is still the same,
        # then the algorithm converged
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [18]:
centroids, cluster_assignment=kmeans(x.values,10,20000,Yrr,dst1)

In [19]:
centroids

array([[0.06557377, 0.00681481, 0.29014845, 0.11538959],
       [0.12295082, 0.05038464, 0.32127512, 0.14296684],
       [0.05737705, 0.0095413 , 0.2919725 , 0.06547088],
       [0.08196721, 0.05665831, 0.31322414, 0.03750677],
       [0.12704918, 0.05640127, 0.3460243 , 0.16174931],
       [0.08196721, 0.01746817, 0.29705951, 0.08506362],
       [0.08401639, 0.04621859, 0.31605026, 0.08159197],
       [0.05327869, 0.018535  , 0.29894801, 0.08196168],
       [0.08401639, 0.04931951, 0.30921392, 0.08451967],
       [0.08278689, 0.03475893, 0.29829025, 0.08777538]])

In [20]:
def distance_euclidean(data,center,j):
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [21]:
Res= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centroids,i)
  Res=Res.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_after _KMeans  with score':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [22]:
Res

cluster Node_before_KMeans  Node_after _KMeans  with score  \
0       0                 36                            44.0   
1       1                  1                            15.0   
2       2                 37                            61.0   
3       3                 40                            30.0   
4       4                 20                            15.0   
5       5                 14                            10.0   
6       6                 51                            42.0   
7       7                 17                            44.0   
8       8                  7                            42.0   
9       9                 33                            10.0   

   distance from center  
0              0.043408  
1              0.033457  
2              0.019254  
3              0.025664  
4              0.027240  
5              0.018616  
6              0.026160  
7              0.019010  
8              0.032340  
9              0.026778

In [30]:
top10=pd.read_csv("top10_result_dolphine1.csv")

In [31]:
top10

Unnamed: 0  DC  BC  CC  EC  TOPSIS
0           0  36  36  36  37      36
1           1  14   1   1  40       1
2           2  54  37  37  14      37
3           3  43  40  40  51      40
4           4  50  20  20  33      20
5           5  15  51  14  45      14
6           6  18  17   7  29      51
7           7  52   7  33  50      17
8           8   9  54  28  21       7
9           9  44  57   8  16      33

In [33]:
top10["k_means"]=Res1["Node_ after _KMeans"].astype(int)
top10["KMeans  with score"]=Res["Node_after _KMeans  with score"].astype(int)
top10

Unnamed: 0  DC  BC  CC  EC  TOPSIS  k_means  KMeans  with score
0           0  36  36  36  37      36       36                  44
1           1  14   1   1  40       1       54                  15
2           2  54  37  37  14      37       37                  61
3           3  43  40  40  51      40       40                  30
4           4  50  20  20  33      20        0                  15
5           5  15  51  14  45      14       14                  10
6           6  18  17   7  29      51       38                  42
7           7  52   7  33  50      17       49                  44
8           8   9  54  28  21       7       30                  42
9           9  44  57   8  16      33       45                  10

In [34]:
top10.to_csv("score_dolphins.csv")