In [1]:
import networkx as nx 
import numpy as np
from numpy.linalg import norm
from  math  import *
import pandas as pd
from sklearn.metrics import pairwise_distances_argmin
from sklearn.metrics import pairwise_distances
import matplotlib.pyplot as plt
%matplotlib inline


In [7]:
top10= pd.read_csv("top10_result.csv")
top10

Unnamed: 0    BC    CC    EC    DC  TOPSIS
0           0   107   107  1912   107     107
1           1  1684  1684  2266  1684    1684
2           2  1912    58  2233  1912    1912
3           3  3437   428  2206  3437    3437
4           4     0   563  2142     0       0
5           5  1085   414  2218  2347    1085
6           6   698   348  2078  2543     698
7           7   567   483  2464  1888     567
8           8    58   376  2123  1800      58
9           9   428   171  1993  1663     428

In [8]:
G1=nx.read_edgelist('facebook_combined.txt',create_using=nx.Graph(),nodetype=int)

In [9]:
G1 = nx.read_edgelist("facebook_combined.txt", nodetype = int)
data = pd.read_csv("TOPSIS_result.csv")
x=data[["DC","BC","CC","EC"]]

In [10]:
x

DC        BC        CC            EC
0     0.258791  0.480518  0.459699  2.606940e-04
1     0.196137  0.337797  0.393606  7.164260e-06
2     0.186974  0.229295  0.350947  9.540696e-02
3     0.135463  0.236115  0.314413  9.531613e-08
4     0.085934  0.146306  0.353343  3.391796e-05
...        ...       ...       ...           ...
4034  0.000495  0.000000  0.178262  6.433195e-14
4035  0.000495  0.000000  0.178262  6.433195e-14
4036  0.000495  0.000000  0.178262  6.446055e-14
4037  0.000248  0.000000  0.178255  6.385265e-14
4038  0.000248  0.000000  0.178255  6.385265e-14

[4039 rows x 4 columns]

In [11]:
def Sn(data ):
  DC=[]
  BC=[]
  CC=[]
  A=[]
  DCEb=[]

  DC=data['DC']
  BC=data['BC']
  CC=data['CC']
  for i in range(len(BC)):
    DCB=(DC[i]+BC[i]+CC[i])/3
    A.append(DCB)
  return A



data=pd.read_csv('TOPSIS_result.csv')
SN=Sn(data)
data['SN']=SN

data.to_csv('moyen_facebook.csv')

In [13]:
SN

[0.39966967101302725,
 0.3091799218832709,
 0.2557388069315442,
 0.22866365944763425,
 0.19519407303931305,
 0.17440388094061843,
 0.1344530624257673,
 0.14693101317053525,
 0.1615779348795121,
 0.1625419011072417,
 0.1597429754447928,
 0.12441622332830743,
 0.15218421155918835,
 0.11955781709416742,
 0.11378837589102093,
 0.12390430144151558,
 0.1548750202381963,
 0.10621150556002917,
 0.10511816802168379,
 0.10611513549135498,
 0.14635727997310008,
 0.10639415870813511,
 0.10467764082201779,
 0.10458888038152254,
 0.10441068107540209,
 0.10485623106340797,
 0.10449972613402224,
 0.10486097815221257,
 0.1045021097157866,
 0.10432397328911634,
 0.10423434270758641,
 0.10432354662433552,
 0.10405795147392449,
 0.10486185650520707,
 0.10405871028619564,
 0.10415168862650592,
 0.10406053559598194,
 0.10396988479683089,
 0.10379297457738919,
 0.1038833552897964,
 0.10379248458046846,
 0.10396998563161138,
 0.10406061172345088,
 0.10361546312596621,
 0.1043355072421116,
 0.10379324122653034

In [14]:
data.drop(columns=['TOPSIS'], inplace=True)
data
AA=pd.read_csv('TOPSIS_result.csv')
inf10=AA.head(10)
inf10

node        DC        CC        BC            EC    TOPSIS
0   107  0.258791  0.459699  0.480518  2.606940e-04  0.913277
1  1684  0.196137  0.393606  0.337797  7.164260e-06  0.695566
2  1912  0.186974  0.350947  0.229295  9.540696e-02  0.496063
3  3437  0.135463  0.314413  0.236115  9.531613e-08  0.488865
4     0  0.085934  0.353343  0.146306  3.391796e-05  0.304321
5  1085  0.016345  0.357852  0.149015  3.164082e-06  0.297379
6   698  0.016840  0.271189  0.115330  1.116876e-09  0.231106
7   567  0.015602  0.328881  0.096310  9.932295e-06  0.193646
8    58  0.002972  0.397402  0.084360  5.898120e-04  0.169464
9   428  0.028479  0.394837  0.064309  5.990065e-04  0.132923

In [15]:
Y=inf10[["DC","BC","CC","EC"]]
Yrr=Y.to_numpy()
Yrr


array([[2.58791481e-01, 4.80518079e-01, 4.59699454e-01, 2.60693991e-04],
       [1.96136701e-01, 3.37797450e-01, 3.93605615e-01, 7.16425979e-06],
       [1.86973749e-01, 2.29295340e-01, 3.50947332e-01, 9.54069615e-02],
       [1.35463101e-01, 2.36115357e-01, 3.14412520e-01, 9.53161293e-08],
       [8.59336305e-02, 1.46305921e-01, 3.53342667e-01, 3.39179617e-05],
       [1.63447251e-02, 1.49015092e-01, 3.57851826e-01, 3.16408207e-06],
       [1.68400198e-02, 1.15330450e-01, 2.71188717e-01, 1.11687629e-09],
       [1.56017831e-02, 9.63103312e-02, 3.28880925e-01, 9.93229483e-06],
       [2.97176820e-03, 8.43602059e-02, 3.97401831e-01, 5.89812015e-04],
       [2.84794453e-02, 6.43090624e-02, 3.94837196e-01, 5.99006469e-04]])

In [ ]:
#fonction 2 k_means 

In [16]:
def kmeans(X, k, maxiter,yrr, seed = None):
    
    n_row, n_col = X.shape

    
    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr

    for itr in range(maxiter):
       
        distances_to_centroids = pairwise_distances(X, centroids, metric = 'euclidean')
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

      
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
     
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [17]:
centers, label = kmeans(x.values,10,20000,Yrr)

In [18]:
centers

array([[2.58791481e-01, 4.80518079e-01, 4.59699454e-01, 2.60693991e-04],
       [1.96136701e-01, 3.37797450e-01, 3.93605615e-01, 7.16425979e-06],
       [1.86973749e-01, 2.29295340e-01, 3.50947332e-01, 9.54069615e-02],
       [1.35463101e-01, 2.36115357e-01, 3.14412520e-01, 9.53161293e-08],
       [3.36800396e-02, 1.26740449e-01, 3.27816034e-01, 1.17538639e-05],
       [2.29796104e-02, 1.93982308e-02, 3.66188497e-01, 8.30760611e-04],
       [1.13856254e-02, 1.02967073e-04, 2.30286579e-01, 1.37995617e-02],
       [8.26088061e-03, 6.53818041e-05, 2.74121583e-01, 7.95701801e-04],
       [3.31094601e-02, 3.80539083e-04, 3.16548559e-01, 2.41186712e-03],
       [8.14939407e-03, 1.37336174e-04, 3.18302120e-01, 8.85898611e-06]])

In [19]:
def distance_euclidean(data,center,j):
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [20]:
Res1= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centers,i)
  Res1=Res1.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_ after _KMeans':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [21]:
Res1

cluster Node_before_KMeans  Node_ after _KMeans  distance from center
0       0                107                107.0              0.000000
1       1               1684               1684.0              0.000000
2       2               1912               1912.0              0.000000
3       3               3437               3437.0              0.000000
4       4                  0                567.0              0.035411
5       5               1085               1465.0              0.014254
6       6                698               3758.0              0.016785
7       7                567                487.0              0.000816
8       8                 58               1456.0              0.002929
9       9                428               1543.0              0.000161

In [22]:
def dist(SN): # fonction pour calculer la distance  a l'aide des scores
 dist0=[]
 ce=[]
 min = 13000 # 1300 l'inicialisation
 for i in range(0,10):
         for j in range(len(SN)):
           dist=sqrt(pow(SN[i],2)+pow(SN[j],2))
           dist0.append(dist)
           A=dist0
 n=10 
 B=[A[i:i+n] for i in range(0,len(A),n)]
 return B
dst=dist(SN)


In [23]:
dst

[[0.5652182692158162,
  0.5052999802329374,
  0.4744872846541107,
  0.4604594608428033,
  0.4447882328449552,
  0.43606485711968446,
  0.42167934728099826,
  0.4258222264736558,
  0.43109543603196415,
  0.43145766367422167],
 [0.43041104090348,
  0.41858719826929813,
  0.42766327896553524,
  0.417168931676346,
  0.4155522114194289,
  0.41843532575939546,
  0.42862818131971114,
  0.4135416905718087,
  0.4132622353613942,
  0.4135169499645813],
 [0.4256245990644641,
  0.41358863975558285,
  0.4131504016889307,
  0.413127921868181,
  0.41308284429432646,
  0.4131956862316985,
  0.41310536027719014,
  0.4131968909209025,
  0.4131059632378982,
  0.41306093658259396],
 [0.41303830830486415,
  0.41306082882299716,
  0.41299382948491015,
  0.4131971138299251,
  0.412994020675951,
  0.41301745746567914,
  0.41299448058803895,
  0.41297164899339966,
  0.41292714551029946,
  0.4129498727859442],
 [0.4129270223454118,
  0.41297167437961035,
  0.4129944997695735,
  0.4128825621486937,
  0.413063849

In [24]:
dst1= np.asarray(dst)
dst1

array([[0.56521827, 0.50529998, 0.47448728, ..., 0.42582223, 0.43109544,
        0.43145766],
       [0.43041104, 0.4185872 , 0.42766328, ..., 0.41354169, 0.41326224,
        0.41351695],
       [0.4256246 , 0.41358864, 0.4131504 , ..., 0.41319689, 0.41310596,
        0.41306094],
       ...,
       [0.1738159 , 0.1738159 , 0.17378568, ..., 0.17378568, 0.17378568,
        0.17378568],
       [0.17378568, 0.17378568, 0.1737555 , ..., 0.1737555 , 0.1737555 ,
        0.1731488 ],
       [0.1731488 , 0.1731488 , 0.17311946, ..., 0.17311946, 0.17309017,
        0.17309017]])

In [25]:
def kmeans(X, k, maxiter,yrr,distance,seed = None):
   
    n_row, n_col = X.shape

    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr

    for itr in range(maxiter):
       
        distances_to_centroids = distance
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

       
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
       
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [26]:
centroids, cluster_assignment=kmeans(x.values,10,20000,Yrr,dst1)

In [27]:
centroids

array([[1.02480848e-02, 8.42355988e-05, 2.74762204e-01, 3.79403603e-03],
       [1.05394735e-02, 5.75901330e-05, 2.76457530e-01, 3.71701883e-03],
       [1.06272232e-02, 1.08466273e-04, 2.75884320e-01, 3.95441946e-03],
       [1.03073434e-02, 4.75516994e-04, 2.75854170e-01, 4.06265812e-03],
       [1.05199925e-02, 6.30001657e-05, 2.77810706e-01, 3.44407636e-03],
       [1.10644193e-02, 3.27189872e-04, 2.78220949e-01, 4.57999955e-03],
       [1.15063506e-02, 1.59315903e-03, 2.77151634e-01, 4.10162991e-03],
       [1.09887062e-02, 1.22828456e-03, 2.79288539e-01, 3.93241064e-03],
       [1.20501576e-02, 1.46505314e-03, 2.74957584e-01, 4.59808878e-03],
       [1.04680887e-02, 6.37891389e-04, 2.74691908e-01, 3.33306390e-03]])

In [28]:
def distance_euclidean(data,center,j):
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [29]:
Res= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centroids,i)
  Res=Res.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_ after _KMeans  with score':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [30]:
Res

cluster Node_before_KMeans  Node_ after _KMeans  with score  \
0       0                107                            213.0   
1       1               1684                           2609.0   
2       2               1912                           2609.0   
3       3               3437                           2609.0   
4       4                  0                           2239.0   
5       5               1085                           2609.0   
6       6                698                           2609.0   
7       7                567                           2239.0   
8       8                 58                           2609.0   
9       9                428                            213.0   

   distance from center  
0              0.003850  
1              0.002616  
2              0.003069  
3              0.003311  
4              0.001620  
5              0.001566  
6              0.002267  
7              0.001402  
8              0.004000  
9              0.003436

In [32]:
top10=pd.read_csv("top10_result.csv")

In [33]:
top10

Unnamed: 0    BC    CC    EC    DC  TOPSIS
0           0   107   107  1912   107     107
1           1  1684  1684  2266  1684    1684
2           2  1912    58  2233  1912    1912
3           3  3437   428  2206  3437    3437
4           4     0   563  2142     0       0
5           5  1085   414  2218  2347    1085
6           6   698   348  2078  2543     698
7           7   567   483  2464  1888     567
8           8    58   376  2123  1800      58
9           9   428   171  1993  1663     428

In [35]:
top10["k_means"]=Res1["Node_ after _KMeans"].astype(int)
top10["k_means with score"]=Res["Node_ after _KMeans  with score"].astype(int)
top10

Unnamed: 0    BC    CC    EC    DC  TOPSIS  k_means  k_means with score
0           0   107   107  1912   107     107      107                 213
1           1  1684  1684  2266  1684    1684     1684                2609
2           2  1912    58  2233  1912    1912     1912                2609
3           3  3437   428  2206  3437    3437     3437                2609
4           4     0   563  2142     0       0      567                2239
5           5  1085   414  2218  2347    1085     1465                2609
6           6   698   348  2078  2543     698     3758                2609
7           7   567   483  2464  1888     567      487                2239
8           8    58   376  2123  1800      58     1456                2609
9           9   428   171  1993  1663     428     1543                 213

In [36]:
top10.to_csv("score_facebook.csv")