In [1]:
import networkx as nx 
import numpy as np
from numpy.linalg import norm
from  math  import *
import pandas as pd
from sklearn.metrics import pairwise_distances_argmin
from sklearn.metrics import pairwise_distances
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
top10= pd.read_csv("top10_result_football.csv")
top10

Unnamed: 0   BC   CC   EC  TOPSIS
0           0    0    0   28       0
1           1   64  106  114      64
2           2  106   41  103     106
3           3   41   80   52      41
4           4   74    4   82      74
5           5   46   28  101      46
6           6   80  114   81      80
7           7   24   35  108      24
8           8   83   25   61      83
9           9    4   67  113       4

In [3]:
G1=nx.read_edgelist('football.txt',create_using=nx.Graph(),nodetype=int)

In [4]:
G1 = nx.read_edgelist("football.txt", nodetype = int)
data = pd.read_csv("TOPSIS_result_football_.csv")
x=data[["DC","BC","CC","EC"]]

In [5]:
x

DC        BC        CC        EC
0    0.105263  0.032490  0.423792  0.106503
1    0.096491  0.033533  0.422222  0.100915
2    0.096491  0.029161  0.435115  0.090415
3    0.087719  0.028823  0.436782  0.079146
4    0.096491  0.025187  0.404255  0.080489
..        ...       ...       ...       ...
110  0.087719  0.006498  0.377483  0.070452
111  0.087719  0.005317  0.391753  0.080728
112  0.061404  0.007790  0.370130  0.048312
113  0.087719  0.004372  0.386441  0.081921
114  0.087719  0.003906  0.373770  0.076032

[115 rows x 4 columns]

In [6]:
def Sn(data ):# fonction qui calcule les scores d'un noeud 
  DC=[]
  BC=[]
  EC=[]
  CC=[]
  A=[]
  DCEb=[]

  DC=data['DC']
  BC=data['BC']
  EC=data['EC']
  CC=data['CC']
  for i in range(len(BC)):
    DCEB=(DC[i]+EC[i]+BC[i]+CC[i])/4
    A.append(DCEB)
  return A



data=pd.read_csv('TOPSIS_result_football_.csv')  
SN=Sn(data)
data['SN']=SN



In [ ]:
SN

[0.16701203950945526,
 0.16329043832306195,
 0.16279539751005734,
 0.1581173291935888,
 0.1516054895395584,
 0.15803147970655249,
 0.15851017971515194,
 0.16381175206452614,
 0.15089487793053313,
 0.16157187161839323,
 0.15644983700895443,
 0.16656328041993326,
 0.16920502069069954,
 0.16224590473594813,
 0.16022229436533045,
 0.15103253976773998,
 0.16579332323739687,
 0.15313266221764602,
 0.16500206813565832,
 0.15807829448834998,
 0.1479942941000968,
 0.155174157851855,
 0.15421525280677567,
 0.1601104331373756,
 0.16398825262951233,
 0.14395801908184322,
 0.14459267872063936,
 0.15234387260678725,
 0.15596281236068574,
 0.15423148079595772,
 0.151608722700626,
 0.14355983310002057,
 0.14884472785094416,
 0.15683500305799486,
 0.16048959868064847,
 0.15629776819596325,
 0.1576623288886758,
 0.14940979549284078,
 0.15252695979551723,
 0.15971203412550405,
 0.15230002492201267,
 0.1491223719737345,
 0.15301004758799994,
 0.1604476028867864,
 0.14864941691369526,
 0.14921350966006555,

In [7]:
data.drop(columns=['TOPSIS'], inplace=True)
data
AA=pd.read_csv('TOPSIS_result_football_.csv')
inf10=AA.head(10)
inf10

node        DC        CC        BC        EC    TOPSIS
0     0  0.105263  0.423792  0.032490  0.106503  0.924560
1    64  0.096491  0.422222  0.033533  0.100915  0.912863
2   106  0.096491  0.435115  0.029161  0.090415  0.819665
3    41  0.087719  0.436782  0.028823  0.079146  0.786272
4    74  0.096491  0.404255  0.025187  0.080489  0.699216
5    46  0.096491  0.422222  0.024139  0.089273  0.681884
6    80  0.096491  0.423792  0.023836  0.089921  0.673942
7    24  0.105263  0.420664  0.023070  0.106250  0.668289
8    83  0.096491  0.402827  0.023046  0.081215  0.640113
9     4  0.096491  0.423792  0.022213  0.103791  0.638511

In [8]:
Y=inf10[["DC","BC","CC","EC"]]
Yrr=Y.to_numpy()
Yrr


array([[0.10526316, 0.03248995, 0.42379182, 0.10650323],
       [0.09649123, 0.03353296, 0.42222222, 0.10091535],
       [0.09649123, 0.02916105, 0.4351145 , 0.0904148 ],
       [0.0877193 , 0.02882282, 0.43678161, 0.07914559],
       [0.09649123, 0.0251868 , 0.40425532, 0.08048861],
       [0.09649123, 0.02413942, 0.42222222, 0.08927305],
       [0.09649123, 0.02383635, 0.42379182, 0.08992131],
       [0.10526316, 0.0230701 , 0.42066421, 0.10624954],
       [0.09649123, 0.02304632, 0.40282686, 0.08121511],
       [0.09649123, 0.02221345, 0.42379182, 0.10379099]])

In [9]:
def kmeans(X, k, maxiter,yrr, seed = None):
    """
    specification de nombre de clusters et le nombre maximal des itiration 
    """
    n_row, n_col = X.shape

    # le choix aleatoire de k parmi la data k
    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr

    for itr in range(maxiter):
        # calcul de la distance entre les centroide et les point de data
        # assigement de chaque point au cluster le plus proche
        distances_to_centroids = pairwise_distances(X, centroids, metric = 'euclidean')
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

        # selection de tout la data qui contient au cluster  i and compte
        # la nouvelle cluster obtenue
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
        #si le centroide est le meme ,
        #l'algorithme converge
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [10]:
centers, label = kmeans(x.values,10,20000,Yrr)

In [11]:
centers

array([[0.10526316, 0.01920727, 0.42262564, 0.11734549],
       [0.09899749, 0.02420873, 0.42224043, 0.10499034],
       [0.09649123, 0.02571228, 0.42704285, 0.08986972],
       [0.08479532, 0.02260309, 0.42656369, 0.07382813],
       [0.07346491, 0.01143054, 0.39458047, 0.06326926],
       [0.09244265, 0.0114171 , 0.3956596 , 0.08423813],
       [0.09590643, 0.01743837, 0.40834809, 0.08689012],
       [0.09649123, 0.00684246, 0.37454359, 0.10704751],
       [0.09046053, 0.00751692, 0.38108819, 0.07754673],
       [0.09763539, 0.01272583, 0.40238022, 0.11028363]])

In [12]:
def distance_euclidean(data,center,j):# fonctio pour calculer la distance euclidean 
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [14]:
Res1= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centers,i)
  Res1=Res1.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_ after _KMeans':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [15]:
Res1

cluster Node_before_KMeans  Node_ after _KMeans  distance from center
0       0                  0                 28.0              0.002301
1       1                 64                  4.0              0.003756
2       2                106                 80.0              0.003754
3       3                 41                 67.0              0.007873
4       4                 74                 49.0              0.005705
5       5                 46                  9.0              0.005111
6       6                 80                 94.0              0.003046
7       7                 24                 59.0              0.007550
8       8                 83                104.0              0.003952
9       9                  4                 34.0              0.004087

In [16]:
def dist(SN):#fonction qui calcule la distance entre les centroides  avec les scores
 dist0=[]
 ce=[]
 min = 13000 # l'inicialisation 
 for i in range(0,10):
         for j in range(len(SN)):
           dist=sqrt(pow(SN[i],2)+pow(SN[j],2))
           dist0.append(dist)
           A=dist0
 n=10 
 B=[A[i:i+n] for i in range(0,len(A),n)]
 return B
dst=dist(SN)


In [ ]:
dst

[[0.2361906913538628,
  0.23357394672532625,
  0.2332281346483855,
  0.22998719775766124,
  0.2255598497065402,
  0.22992818426489248,
  0.23025746114824946,
  0.23393869165992534,
  0.2250828414757072,
  0.23237575398345325],
 [0.22884399236430972,
  0.23587358420424523,
  0.23774642030543364,
  0.23284491608084168,
  0.2314394196173125,
  0.2251751527362684,
  0.23533050667350336,
  0.22658912943689843,
  0.23477372900337948,
  0.22996036295295183],
 [0.2231486778524439,
  0.22797377175048067,
  0.2273221624465278,
  0.23136199372530025,
  0.23406231721827545,
  0.2204924774206054,
  0.2209073653835876,
  0.22605680007896437,
  0.22851131302533428,
  0.22733317181973625],
 [0.2255620228230434,
  0.22023271105994588,
  0.22371359893875353,
  0.2291074846558032,
  0.23162455099963702,
  0.2287400570170142,
  0.22967462047799017,
  0.22408995588896963,
  0.2261802263805817,
  0.23108646690278947],
 [0.22602725263196366,
  0.22389842153123965,
  0.2265062824823847,
  0.23159545464715786,

In [17]:
dst1= np.asarray(dst)
dst1

array([[0.23619069, 0.23357395, 0.23322813, ..., 0.23393869, 0.22508284,
        0.23237575],
       [0.22884399, 0.23587358, 0.23774642, ..., 0.22658913, 0.23477373,
        0.22996036],
       [0.22314868, 0.22797377, 0.22732216, ..., 0.2260568 , 0.22851131,
        0.22733317],
       ...,
       [0.22287339, 0.21898982, 0.21784366, ..., 0.21897596, 0.21756398,
        0.21480666],
       [0.21190305, 0.21380556, 0.21339138, ..., 0.21479936, 0.21480601,
        0.2118777 ],
       [0.21322615, 0.21291027, 0.2113175 , ..., 0.20240351, 0.2138625 ,
        0.21077702]])

In [18]:
def kmeans(X, k, maxiter,yrr,distance,seed = None): # fonction K-means
  # specification de nombre de clusters et le nombre maximal des itiration 
    n_row, n_col = X.shape
    # le choix aleatoire de k parmi la data k
    if seed is not None:
        np.random.seed(seed)
    
    rand_indices = np.random.choice(n_row, size = k)
    centroids =yrr # l'inicialisation

    for itr in range(maxiter):
        # calcul de la distance entre les centroides et les points de data
        # assigement de chaque point au cluster le plus proche
        distances_to_centroids = distance # la distance avec score 
        cluster_assignment = np.argmin(distances_to_centroids, axis = 1)

       # selection de tout la data qui contient au cluster  i and compte
        # la nouvelle cluster obtenue
        new_centroids = np.array([X[cluster_assignment == i].mean(axis = 0) for i in range(k)])
        
         #si le centroide est le meme ,
        #l'algorithme converge
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids
    
    return centroids, cluster_assignment


In [19]:
centroids, cluster_assignment=kmeans(x.values,10,20000,Yrr,dst1)

In [20]:
centroids

array([[0.09473684, 0.01448332, 0.4005933 , 0.08664985],
       [0.09035088, 0.0152756 , 0.40339428, 0.0831871 ],
       [0.09824561, 0.01287802, 0.3978924 , 0.10330191],
       [0.09298246, 0.01306537, 0.39715602, 0.09352966],
       [0.08421053, 0.01205764, 0.39690085, 0.08191535],
       [0.09438596, 0.0140212 , 0.4031966 , 0.09633171],
       [0.09122807, 0.01234317, 0.39911906, 0.08854131],
       [0.09532164, 0.0120323 , 0.39502834, 0.0929394 ],
       [0.09532164, 0.01433045, 0.40064477, 0.09033899],
       [0.09122807, 0.01205571, 0.39435942, 0.08672548]])

In [22]:
def distance_euclidean(data,center,j):#fonction pour calculer la distance euclidean
    T= pd.DataFrame()
    for i in range(len(data)):
        distance=sqrt((data['DC'][i]-center[j][0])**2+(data['BC'][i]-center[j][1])**2+
                           (data['CC'][i]-center[j][2])**2+(data['EC'][i]-center[j][3])**2)
        T=T.append({'node':data['node'][i], 'cluster':str(j),'distance from center':distance},ignore_index=True)
    return T.sort_values(by='distance from center')

In [30]:
Res= pd.DataFrame()
for i in range(10):
  T=distance_euclidean(data,centroids,i)
  Res=Res.append({'cluster':str(i), 'Node_before_KMeans':str(inf10['node'][i]),
                    'Node_ after _KMeans  with score':int(T.head(1)['node']),
                    'distance from center':float(T.head(1)['distance from center'])},ignore_index=True)

In [31]:
Res

cluster Node_before_KMeans  Node_ after _KMeans  with score  \
0       0                  0                             95.0   
1       1                 64                             19.0   
2       2                106                             39.0   
3       3                 41                             16.0   
4       4                 74                             99.0   
5       5                 46                             18.0   
6       6                 80                             51.0   
7       7                 24                             16.0   
8       8                 83                              7.0   
9       9                  4                             55.0   

   distance from center  
0              0.001969  
1              0.004348  
2              0.002217  
3              0.004885  
4              0.005519  
5              0.006246  
6              0.005083  
7              0.003497  
8              0.004242  
9              0.005794

In [32]:
top10=pd.read_csv("top10_result_football.csv")

In [33]:
top10

Unnamed: 0   BC   CC   EC  TOPSIS
0           0    0    0   28       0
1           1   64  106  114      64
2           2  106   41  103     106
3           3   41   80   52      41
4           4   74    4   82      74
5           5   46   28  101      46
6           6   80  114   81      80
7           7   24   35  108      24
8           8   83   25   61      83
9           9    4   67  113       4

In [35]:
top10["k_means"]=Res1["Node_ after _KMeans"]
top10["k_means with score"]=Res["Node_ after _KMeans  with score"]
top10

Unnamed: 0   BC   CC   EC  TOPSIS  k_means  k_means with score
0           0    0    0   28       0     28.0                95.0
1           1   64  106  114      64      4.0                19.0
2           2  106   41  103     106     80.0                39.0
3           3   41   80   52      41     67.0                16.0
4           4   74    4   82      74     49.0                99.0
5           5   46   28  101      46      9.0                18.0
6           6   80  114   81      80     94.0                51.0
7           7   24   35  108      24     59.0                16.0
8           8   83   25   61      83    104.0                 7.0
9           9    4   67  113       4     34.0                55.0

In [36]:
top10.to_csv("score_football.csv")